### ISSUE TITLE
KeyError: 'apperance_index'

### ISSUE THREAD

**Issue by daviduarte** [brjathu/LART#16]
Hi, thank you for your excellent work. 

I followed [this issue](https://github.com/brjathu/LART/issues/3) to make PHALP save features for my dataset videos. I have to set the **save_fast_tracks = True** on phalp/configs/base.py, as well as **save_fast_tracks = true** on outputs/.hydra/config.yaml to make the [post_process](https://github.com/brjathu/PHALP/commit/475b1d191d45fb5703cb3f8f1c02212a0c05dc6d) function be executed. However, I'm getting the following error:

```
Error executing job with overrides: ['video.source=assets/gymnasts_short.mp4', '+half=True']
Traceback (most recent call last):
  File "/home/lecun/LART_dev/scripts/demo.py", line 114, in main
    lart_model.postprocessor.run_lart(pkl_path)
  File "/home/lecun/LART_dev/venv/lib/python3.10/site-packages/phalp/visualize/postprocessor.py", line 102, in run_lart
    final_visuals_dic  = self.post_process(final_visuals_dic, save_fast_tracks=self.cfg.post_process.save_fast_tracks, video_pkl_name=video_pkl_name)
  File "/home/lecun/LART_dev/venv/lib/python3.10/site-packages/phalp/visualize/postprocessor.py", line 42, in post_process
    for idx, appe_idx in enumerate(smoothed_fast_track_['apperance_index']):
KeyError: 'apperance_index'
```

I'm using default configs that come from LART repository. I'm also using **dev branch** to run my code in half precision.

Do you have any suggestion for why this is happening?

Thanks

**Comment by brjathu** [comment]
Apologies for the late reply, is the resolved?

**Comment by daviduarte** [comment]
Hello!

Unfortunately, the problem hasn't been solved. It seems that PHALP doesn't generate some features needed later in the code.

The "apperance_index" is explicity expected by the PHALP code in [this line of code ](https://github.com/brjathu/PHALP/blob/master/phalp/visualize/postprocessor.py#L42), but it is missing from the "results_temporal" .pkl track file (the one which have each frame from video). If I inspect some random .pkl file generated by PHALP: 

```
import joblib
pkl = joblib.load("demo_0.pkl")
pkl['outputs//_DEMO/0/img/001092.jpg'].keys()
```

I can see that the "apperance_index" is missing:

dict_keys(['time', 'shot', 'frame_path', 'tracked_ids', 'tracked_bbox', 'tid', 'bbox', 'tracked_time', 'center', 'scale', 'size', 'img_path', 'img_name', 'class_name', 'conf', 'annotations', 'smpl', 'camera', 'camera_bbox', '3d_joints', '2d_joints', 'mask', 'extra_data', 'label'])

I cloned the PHALP repo, and I performed a grep -r -i "apperance_index" without finding anything. Perhaps this part of the code is associated with the HIERA backend, which isn't available yet?

**Comment by vtn98** [comment]
I have the same issue
