### ISSUE TITLE
Evaluate Problem

### ISSUE THREAD

**Issue by actionrecognitioners** [brjathu/LART#33]
When I tried to evaluate the lart model, I executed your instructions and installed and downloaded all the dependent environments and data sets, but encountered an error: 
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/phalp/3D/smpl_mean_params.npz'
I'm devastated. I can't run through the code.

**Comment by actionrecognitioners** [comment]
i had resolve this problem through run ‘Demo on videos’，but I downloaded the data set, installed the virtual environment, downloaded checkpint and related content, and when I ran the evaluate code, I encountered an error:
Traceback (most recent call last):
  File "/mnt/data1/LART1/lart/train.py", line 166, in main
    metric_dict, _ = train(cfg)
  File "/mnt/data1/LART1/lart/utils/utils.py", line 62, in wrap
    raise ex
  File "/mnt/data1/LART1/lart/utils/utils.py", line 59, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/mnt/data1/LART1/lart/train.py", line 146, in train
    trainer.validate(model=model, datamodule=datamodule, ckpt_path=ckpt_path)
  File "/mnt/data1/anaconda3/envs/lart1/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 639, in validate
    return call._call_and_handle_interrupt(
  File "/mnt/data1/anaconda3/envs/lart1/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 46, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/mnt/data1/anaconda3/envs/lart1/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
    return function(*args, **kwargs)
  File "/mnt/data1/anaconda3/envs/lart1/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 679, in _validate_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/mnt/data1/anaconda3/envs/lart1/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 943, in _run
    call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
  File "/mnt/data1/anaconda3/envs/lart1/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 102, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/mnt/data1/anaconda3/envs/lart1/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 189, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/mnt/data1/LART1/lart/datamodules/phalp_datamodule.py", line 73, in setup
    self.data_val   = PHALP_action_dataset(self.hparams.cfg, train=False)
  File "/mnt/data1/LART1/lart/datamodules/components/phalp_action_datatset.py", line 81, in __init__
    self.track2video = np.array(self.track2video)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (97148,) + inhomogeneous part.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by actionrecognitioners** [comment]
i had resolved！#30
