### ISSUE TITLE
Can't unpickle the generated pickle files

### ISSUE THREAD

**Issue by saraswat** [brjathu/LART#4]
I generated output from my own videoclip, running on a `python 3.10.12` notebook in Google collab. (`sys.version` within the notebook agrees with what is produced by `!python --version`.) I used the given command:
```
!python scripts/demo.py video.source="../../4dhumans/inputs/round5_clip.mp4"
```

However, I cannot read any of the `pkl` files in `outputs/results_temporal_fast`. I get:
```
with open("demo_round5_clip_100_38.pkl", "rb") as f:
  z = pkl.load(f)
```
==>
```
UnpicklingError                           Traceback (most recent call last)
[<ipython-input-21-802b467ad1f5>](https://localhost:8080/#) in <cell line: 1>()
      1 with open("demo_round5_clip_100_38.pkl", "rb") as f:
----> 2   z = pkl.load(f)

UnpicklingError: invalid load key, '\x0c'.
```

Even running `python -m pickletools <filename>` gives an error:
```
191: \x94         MEMOIZE    (as 22)
  192: \x88         NEWTRUE
  193: \x8c         SHORT_BINUNICODE 'numpy_array_alignment_bytes'
  222: \x94         MEMOIZE    (as 23)
  223: K            BININT1    16
  225: u            SETITEMS   (MARK at 69)
  226: b        BUILD
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/pickletools.py", line 2883, in <module>
    dis(args.pickle_file[0], args.output, None,
  File "/usr/lib/python3.10/pickletools.py", line 2448, in dis
    for opcode, arg, pos in genops(pickle):
  File "/usr/lib/python3.10/pickletools.py", line 2285, in _genops
    raise ValueError("at position %s, opcode %r unknown" % (
ValueError: at position 227, opcode b'\x0c' unknown
```

Any clue?

**Comment by brjathu** [comment]
Hi, Can you please try with joblib?

```python
import joblib

data = joblib.load("<path to pkl>")
print(data.keys())
```

**Comment by saraswat** [comment]
Failed.
```
import job lib
x = joblib.load("/Users/vijaysaraswat/Downloads/demo_round5_clip.pkl")
```
==>
```
KeyError                                  Traceback (most recent call last)
Input In [57], in <module>
----> 1 x = joblib.load("/Users/vijaysaraswat/Downloads/demo_round5_clip.pkl")

File ~/anaconda3/envs/py310/lib/python3.9/site-packages/joblib/numpy_pickle.py:587, in load(filename, mmap_mode)
    581             if isinstance(fobj, str):
    582                 # if the returned file object is a string, this means we
    583                 # try to load a pickle file generated with an version of
    584                 # Joblib so we load it with joblib compatibility function.
    585                 return load_compatibility(fobj)
--> 587             obj = _unpickle(fobj, filename, mmap_mode)
    588 return obj

File ~/anaconda3/envs/py310/lib/python3.9/site-packages/joblib/numpy_pickle.py:506, in _unpickle(fobj, filename, mmap_mode)
    504 obj = None
    505 try:
--> 506     obj = unpickler.load()
    507     if unpickler.compat_mode:
    508         warnings.warn("The file '%s' has been generated with a "
    509                       "joblib version less than 0.10. "
    510                       "Please regenerate this pickle file."
    511                       % filename,
    512                       DeprecationWarning, stacklevel=3)

File ~/anaconda3/envs/py310/lib/python3.9/pickle.py:1212, in _Unpickler.load(self)
   1210             raise EOFError
   1211         assert isinstance(key, bytes_types)
-> 1212         dispatch[key[0]](self)
   1213 except _Stop as stopinst:
   1214     return stopinst.value

KeyError: 188
```

**Comment by brjathu** [comment]
If you running it on collab, are you using the dev branch?

**Comment by saraswat** [comment]
No. I did a `git clone` of the code, and then a `pip instal -e .[all]` (I have been working last few days with PHALP, 4DHumans and LART, and may have the `[all]` mixed up. But no, I did not switch to a `dev` branch, worked with head in all cases.)

**Comment by brjathu** [comment]
I see if you only install lart with `pip install -e .[demo]` it will install both 4DHumans and PHALP. Perhaps you could please try a new environment with only installing lart? I just tried this on my end on `jump.mp4` and I was able to read all the `.pkl` files under `results_temporal_fast`.

**Comment by saraswat** [comment]
No luck. Similar error. Actually let me focus om just getting PHALP pkl files read first. Will try tomorrow.

**Comment by faezehprb** [comment]
Hello
Thanks for your great work.
I have the same problem. I can't unpickle the generated pickles in both LART and PHALP output folders.(I use google colab)

**Comment by brjathu** [comment]
@saraswat any updates on this? Thanks.

**Comment by brjathu** [comment]
closing this due to inactivity. please feel free to reopen if needed.
