### ISSUE TITLE
Dear author, I am always unable to install the detectron2 dependency

### ISSUE THREAD

**Issue by striveforx** [brjathu/LART#7]
The error is as follows：
ERROR: Could not build wheels for detectron2, which is required to install pyproject.toml-based projects

I am a beginner in computer vision. I want to try to run the demo by myself, but during the installation of the environment, there will always be errors. I guess it is a problem of version incompatibility. If you can take the time to help me solve this problem, I will be very grateful.

**Comment by niazahamd89** [comment]
build environment using Python 3.10. worked for me in Ubuntu.

**Comment by striveforx** [comment]
> build environment using Python 3.10. worked for me in Ubuntu.

Yes, the environment I use is python3.10 and ubuntu, but there will still be this error. Could it be that I changed the image source of conda? I changed my domestic image channel.

**Comment by brjathu** [comment]
@striveforx could you please share your logs/errors?

**Comment by striveforx** [comment]
@brjathu Thanks. I have already solved this problem.But I encountered another problem in demo

python scripts/demo.py video.source="assets/jump.mp4"

[07/18 10:23:19] INFO     OpenGL_accelerate module       acceleratesupport.py:13
                          loaded                                                
                 INFO     Using accelerated ArrayDatatype   arraydatatype.py:280
--2023-07-18 10:23:23--  https://github.com/classner/up/raw/master/models/3D/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl
正在解析主机 github.com (github.com)... 20.205.243.166
正在连接 github.com (github.com)|20.205.243.166|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
重试中。

--2023-07-18 10:23:43--  (尝试次数： 2)  https://github.com/classner/up/raw/master/models/3D/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl
正在连接 github.com (github.com)|20.205.243.166|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (连接被对方重设)。
重试中。

--2023-07-18 10:24:05--  (尝试次数： 3)  https://github.com/classner/up/raw/master/models/3D/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl
正在连接 github.com (github.com)|20.205.243.166|:443... 失败：拒绝连接。
正在解析主机 github.com (github.com)... 20.205.243.166
正在连接 github.com (github.com)|20.205.243.166|:443... 失败：拒绝连接。
Error executing job with overrides: ['video.source=assets/jump.mp4']
Traceback (most recent call last):
  File "/home/leizi/github/LART/scripts/demo.py", line 90, in main
    phalp_tracker = HMR2_4dhuman(cfg)
  File "/home/leizi/github/LART/scripts/demo.py", line 48, in __init__
    super().__init__(cfg)
  File "/home/leizi/anaconda3/envs/lart/lib/python3.10/site-packages/phalp/trackers/PHALP.py", line 49, in __init__
    self.cached_download_from_drive()
  File "/home/leizi/anaconda3/envs/lart/lib/python3.10/site-packages/phalp/trackers/PHALP.py", line 634, in cached_download_from_drive
    convert_pkl('basicModel_neutral_lbs_10_207_0_v1.0.0.pkl')
  File "/home/leizi/anaconda3/envs/lart/lib/python3.10/site-packages/phalp/utils/utils.py", line 136, in convert_pkl
    with open(old_pkl, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'basicModel_neutral_lbs_10_207_0_v1.0.0.pkl'

**Comment by brjathu** [comment]
Update collab has a code snippet to get the body model. You can run the following in the root directory to get the body models.

```bash
wget https://github.com/classner/up/raw/master/models/3D/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl
mkdir data/
mv basicModel_neutral_lbs_10_207_0_v1.0.0.pkl data/
```

**Comment by brjathu** [comment]
closing due to inactivity, please reopen if you have any questions.
